### ISSUE TITLE
Possible legal issues with the logo

### ISSUE THREAD

**Issue by KOLANICH** [Nuitka/Nuitka-website#19]
I once wanted to use a logo in colors of python in order to highlight that my project is intended to be used with python (it is essentially python bindings to some third-party code), but feeled like they can be trademarked.

I have contacted the email and asked for clarifiaction and permission. I was told that currently they don't intend to trademark python colors and that if I start using my logo, I'd "be" a my trademark (damn this legal shit, I wish there would be no trademark laws at all!). But the colors are already a de-facto trademark.

I asked if they can either give me a digitally signed text that the use of the colors in my logo is not considered trademark violation, or change their trademark policy to clarify which uses of colors are explicitly allowed. I was answered that this is the decision which is up to the board, and the board won't do that for me unless maybe for a lot of money.

IMHO this FUD situation is a bit annoying.

https://pyright.blogspot.com/2011/02/svg-xml-and-python-logo.html
https://github.com/Nuitka/Nuitka-website/issues/19
https://github.com/PyAV-Org/PyAV/issues/728
https://github.com/derb12/mcetl/issues/13
https://github.com/ReagentX/Logria-py/issues/147
https://github.com/python-trio/trio/issues/1828
https://github.com/amcc1996/symbeam/issues/7

**Comment by kayhayen** [comment]
I have explicitly asked about Nuika logo the PSF an got their OK. Even before using it. Easy.

**Comment by KOLANICH** [comment]
>I have explicitly asked

So did I, but they have refused to give me anything that is enough to kill a lawsuit, if in future PSF wanted more money and started suing the projects using their trademarks claiming that what they have given was not actually a permission or it was invalid by any reason.
