### ISSUE TITLE
Improve dependencies for python environment management

### ISSUE THREAD

**Issue by xinetzone** [Nuitka/Nuitka-website#55]
``pipenv`` may have a variety of dependency issues, using [pdm](https://pdm.fming.dev/latest/) may be a better choice.

**Comment by kayhayen** [comment]
It might be, can you demonstrate it in a PR @xinetzone, that would be very helpful. I am not at all bound by soul to pipenv, but I am pretty sure I do not want poetry. Never used pdm so far. Many of the feature highlights do not apply to this use, as it's not being deployed, but only used locally to build, but go ahead, how hard can it be?

**Comment by xinetzone** [comment]
I'm working on a way to do it. Use PDM in Continuous Integration[#](https://pdm.fming.dev/latest/usage/advanced/#use-pdm-in-continuous-integration)

**Comment by kayhayen** [comment]
Not sure how beneficial that is, I want to develop the web site offline without push/build cycles on CI most of the time.

**Comment by xinetzone** [comment]
solution: https://github.com/Nuitka/Nuitka-website/tree/new-tool

**Comment by kayhayen** [comment]
We are going to switch to using devcontainer, the tool to use inside of that is pretty irrelevant, can be system wide installs, that wouldn't be an issue there.
