### ISSUE TITLE
Burger menu does not work

### ISSUE THREAD

**Issue by ubmarco** [Nuitka/Nuitka-website#67]
For smaller screens, the burger menu button does not work.
Not on desktop, not on mobile, for all of Chrome, Safari and Firefox.

![nuitka_burger](https://github.com/Nuitka/Nuitka-website/assets/839934/f81ec7f4-97d3-4ba8-b9f1-19a0e9440acb)

**Comment by kayhayen** [comment]
Oh, that's pretty bad, I confirmed it does work on my Firefox Windows desktop just now.

![grafik](https://github.com/Nuitka/Nuitka-website/assets/4226920/959b4349-dfb7-4cf4-9a07-997e7de0d5db)

**Comment by kayhayen** [comment]
On macOS it doesn't work in my desktop Firefox just now. I even disabled my AdBlocker, I believe this has to be some JavaScript, and that's really, really strange to happen.

I saw in its console this: 

![grafik](https://github.com/Nuitka/Nuitka-website/assets/4226920/afa3a149-ab5f-4a92-8908-d2ae4af2c653)

I think `DOCUMENTATION_OPTIONS` rings a bell for sure, I will have to investigate.

**Comment by kayhayen** [comment]
Also not sure, if the hamburger menu "working" definition is correct on my side. With the recent Sphinx upgrade, what was previously inline JavaScript, became an external file, and I added it at the end of the "set 1", but I guess it may well be used by code before that, so it should be at the top.

**Comment by kayhayen** [comment]
With some luck, I just pushed the correction, since that JavaScript error would go away. Not sure why it's unrecoverable in some cases, or used in others. I also checked right now, mobile doesn't work either, which is really bad.

**Comment by kayhayen** [comment]
I just confirmed, the uncached form of the site now does it correctly on mobile and macOS too. No idea why it ever worked on Windows still, that seems like a strange difference to encounter. Once Cloudfare refreshes border caches, it will be generally good. Thanks for letting me know, this is of course very critical.

**Comment by ubmarco** [comment]
Nice, works now also for me!
