### ISSUE TITLE
Website down.

### ISSUE THREAD

**Issue by TokenChingy** [Nuitka/Nuitka-website#8]
Not sure as to why this is, but can’t seem to reach ‘nuitka.net’.

**Comment by kayhayen** [comment]
Thanks for the report, I rebooted it. This is happening a lot, I will move it to a VM shortly.

**Comment by kayhayen** [comment]
By a lot, I mean two times in the last 2 days, but I think it means hardware is getting weak, because there never was an issue before for years.
